services:

## Database

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Mount our init script to run on first startup
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: unless-stopped


## Backend

  backend:
    build: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network
    depends_on:
      - database
    restart: unless-stopped


## Frontend

  frontend:
    build: ./frontend
    networks:
      - app-network
    restart: unless-stopped

## Nginx as a Reverse Proxy
  
  nginx:
    image: nginx:alpine
    ports:
      # Map EC2 host ports to Nginx container ports
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Add this line to add the ssl-certificate 
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped


networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
