events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    # 1. Redirect all standard HTTP traffic to HTTPS
    server {
        listen 80;
        server_name shalindevops.shalintimalsina.com.np;
        return 301 https://$host$request_uri;
    }

    # 2. Handle the secure HTTPS traffic
    server {
        listen 443 ssl;
        server_name shalindevops.shalintimalsina.com.np;

        # Point Nginx to the Let's Encrypt certificates we mounted
        ssl_certificate /etc/letsencrypt/live/shalindevops.shalintimalsina.com.np/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/shalindevops.shalintimalsina.com.np/privkey.pem;
        
        # Production security headers for SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Route for the Frontend UI
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Route for the Backend API
        location /api {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
